<internal_error>
<sub_system>ERR</sub_system>
<callstack>
	0x7f75b5320d31: ccl_err + 0x9d31 (_ZN15ERR_STACKWALKER15get_stack_traceEPPKviiPv + 0xb3)
	0x7f75b5323d73: ccl_err + 0xcd73 (_Z14err_terminatorv + 0x77)
	0x7f75b04a8c12: dinkum_alt + 0x1dc12 (_ZSt9terminatev + 0x12)
	0x7f75ae6390c6: stdc++.so.6 + 0xbd0c6 (__cxa_rethrow + 0x46)
	0x7f75b302c51f: QtCore.so.4 + 0x18a51f (_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 0x34f)
	0x7f75b3030d4b: QtCore.so.4 + 0x18ed4b (_ZN16QCoreApplication4execEv + 0xbb)
	   0x407dc1: quartus + 0x7dc1 (__gxx_personality_v0 + 0x3b9)
	0x7f75b7bf9b9a: ccl_msg + 0x3bb9a (_Z15msg_main_threadPv + 0x10)
	0x7f75b4cca5bc: ccl_thr + 0x75bc (thr_final_wrapper + 0xc)
	0x7f75b7bfa801: ccl_msg + 0x3c801 (_Z18msg_thread_wrapperPFPvS_ES_ + 0x5b)
	   0x416e45: quartus + 0x16e45 (_Z18mem_thread_wrapperPFPvS_ES_ + 0xc5)
	0x7f75b532641d: ccl_err + 0xf41d (_Z18err_thread_wrapperPFPvS_ES_ + 0x27)
	0x7f75b4cca99c: ccl_thr + 0x799c (thr_thread_wrapper + 0x15)
	0x7f75b7c0c41d: ccl_msg + 0x4e41d (_Z12msg_exe_mainiPPKcPFiiS1_E + 0x96)
	   0x407e85: quartus + 0x7e85 (__gxx_personality_v0 + 0x47d)
	0x7f75addde995: c.so.6 + 0x21995 (__libc_start_main + 0xf5)
	   0x407c99: quartus + 0x7c99 (__gxx_personality_v0 + 0x291)
</callstack>
<error>*** Fatal Error: Unhandled Exception</error>
<date>Tue Feb 11 13:19:14 2014
</date>
<version>Version 13.1.0 Build 162 10/23/2013 SJ Web Edition</version>
</internal_error>